using System.Collections.Generic;
using System.Linq;

namespace Archipelago;

public static class Data
{
    public static Dictionary<ItemProperties.ItemID, string> LocationMap = new Dictionary<ItemProperties.ItemID, string>(){
        {ItemProperties.ItemID.AmuletOfSol, "Hall of the Phantoms - Amulet of Sol"},
        {ItemProperties.ItemID.BanishSpell, "Gorgon Tomb - Banish Spell"},
        {ItemProperties.ItemID.GorgonHeart, "Gorgon Tomb - Gorgonheart"},
        {ItemProperties.ItemID.GriffonClaw, "Hall of the Phantoms - Griffon Claw"},
        {ItemProperties.ItemID.IcarusEmblem, "Ruins of Ash - Icarus Emblem"},
        {ItemProperties.ItemID.LunarianBow, "Catacombs - Lunarian Bow"},
        {ItemProperties.ItemID.RingOfTheAncients, "Gorgon Tomb - Ring of the Ancients"},
        {ItemProperties.ItemID.SwordOfMirrors, "Gorgon Tomb - Sword of Mirrors"},
        {ItemProperties.ItemID.GorgonEyeRed, "Gorgon Tomb - Gorgon Eye (Red)"},
        {ItemProperties.ItemID.GorgonEyeBlue, "Mechanism - Gorgon Eye (Blue)"},
        {ItemProperties.ItemID.GorgonEyeGreen, "Ruins of Ash - Gorgon Eye (Green)"},
        {ItemProperties.ItemID.DeadMaidensRing, "Hall of the Phantoms - Dead Maiden's Ring"},
        {ItemProperties.ItemID.LinusMap, "Gorgon Tomb - Linus' Map"},
        {ItemProperties.ItemID.AthenasBell, "Hall of the Phantoms - Athena's Bell"},
        {ItemProperties.ItemID.VoidCharm, "Gorgon Tomb - Void Charm"},
        {ItemProperties.ItemID.CloakOfLevitation, "Mechanism - Cloak of Levitation"},
        {ItemProperties.ItemID.AdornedKey, "Tower Roots - Adorned Key"},
        {ItemProperties.ItemID.PrincesCrown, "Cyclops Den - Prince's Crown"},
        {ItemProperties.ItemID.AscendantKey, "Gorgon Tomb - Ascendant Key"},
        {ItemProperties.ItemID.TalariaBoots, "Mechanism - Talaria Boots"},
        {ItemProperties.ItemID.MonsterBall, "Gorgon Tomb - Monster Ball"},
        {ItemProperties.ItemID.BloodChalice, "The Apex - Blood Chalice"},
        {ItemProperties.ItemID.MorningStar, "Serpent Path - Morning Star"},
        {ItemProperties.ItemID.CyclopsIdol, "Mechanism - Cyclops Idol"},
        {ItemProperties.ItemID.BoreasGauntlet, "Hall of the Phantoms - Boreas Gauntlet"},
        {ItemProperties.ItemID.FamiliarGil, "Catacombs - Gil"},
        {ItemProperties.ItemID.MagicBlock, "Cathedral - Magic Block"},
    };

    public static Dictionary<string, ItemProperties.ItemID> ItemMap = new Dictionary<string, ItemProperties.ItemID>(){
        {"Amulet of Sol", ItemProperties.ItemID.AmuletOfSol},
        {"Banish Spell", ItemProperties.ItemID.BanishSpell},
        {"Gorgonheart", ItemProperties.ItemID.GorgonHeart},
        {"Griffon Claw", ItemProperties.ItemID.GriffonClaw},
        {"Icarus Emblem", ItemProperties.ItemID.IcarusEmblem},
        {"Lunarian Bow", ItemProperties.ItemID.LunarianBow},
        {"Ring of the Ancients", ItemProperties.ItemID.RingOfTheAncients},
        {"Sword of Mirrors", ItemProperties.ItemID.SwordOfMirrors},
        {"Gorgon Eye (Red)", ItemProperties.ItemID.GorgonEyeRed},
        {"Gorgon Eye (Blue)", ItemProperties.ItemID.GorgonEyeBlue},
        {"Gorgon Eye (Green)", ItemProperties.ItemID.GorgonEyeGreen},
        {"Dead Maiden's Ring", ItemProperties.ItemID.DeadMaidensRing},
        {"Linus' Map", ItemProperties.ItemID.LinusMap},
        {"Athena's Bell", ItemProperties.ItemID.AthenasBell},
        {"Void Charm", ItemProperties.ItemID.VoidCharm},
        {"Cloak of Levitation", ItemProperties.ItemID.CloakOfLevitation},
        {"Adorned Key", ItemProperties.ItemID.AdornedKey},
        {"Prince's Crown", ItemProperties.ItemID.PrincesCrown},
        {"Ascendant Key", ItemProperties.ItemID.AscendantKey},
        {"Talaria Boots", ItemProperties.ItemID.TalariaBoots},
        {"Monster Ball", ItemProperties.ItemID.MonsterBall},
        {"Blood Chalice", ItemProperties.ItemID.BloodChalice},
        {"Morning Star", ItemProperties.ItemID.MorningStar},
        {"Cyclops Idol", ItemProperties.ItemID.CyclopsIdol},
        {"Boreas Gauntlet", ItemProperties.ItemID.BoreasGauntlet},
        {"Gil", ItemProperties.ItemID.FamiliarGil},
        {"Magic Block", ItemProperties.ItemID.MagicBlock},
    };

    public static Dictionary<string, string> IconMap = new Dictionary<string, string>(){
        {"Amulet of Sol", "Item_AmuletOfSol"},
        {"Banish Spell", "Item_BanishSpell"},
        {"Gorgonheart", "Item_GorgonHeart"},
        {"Griffon Claw", "Item_GriffonClaw"},
        {"Icarus Emblem", "Item_IcarusEmblem"},
        {"Lunarian Bow", "Item_LunarianBow"},
        {"Ring of the Ancients", "Item_RingOfTheAncients"},
        {"Sword of Mirrors", "Item_SwordOfMirrors"},
        {"Gorgon Eye (Red)", "Item_GorgonEyeRed"},
        {"Gorgon Eye (Blue)", "Item_GorgonEyeBlue"},
        {"Gorgon Eye (Green)", "Item_GorgonEyeGreen"},
        {"Dead Maiden's Ring", "Item_DeadMaidensRing"},
        {"Linus' Map", "Item_LinusMap"},
        {"Athena's Bell", "Item_AthenasBell"},
        {"Void Charm", "Item_VoidCharm"},
        {"Cloak of Levitation", "Item_CloakOfLevitation"},
        {"Adorned Key", "Item_AdornedKey"},
        {"Prince's Crown", "Item_PrincesCrown"},
        {"Ascendant Key", "Item_AscendantKey"},
        {"Talaria Boots", "Item_TalariaBoots"},
        {"Monster Ball", "Item_MonsterBall"},
        {"Blood Chalice", "Item_BloodChalice"},
        {"Morning Star", "Item_MorningStar"},
        {"Cyclops Idol", "Item_CyclopsIdol"},
        {"Boreas Gauntlet", "Item_BoreasGauntlet"},
        {"Gil", "Item_FamiliarGil"},
        {"Magic Block", "Item_MagicBlock"},
        {"Max HP +1", "Item_HealthStone_1"},
        {"Max HP +2", "Item_HealthStone_1"},
        {"Max HP +3", "Item_HealthStone_1"},
        {"Max HP +5", "Item_HealthStone_1"},
        {"Attack +1", "Item_HealthStone_1"},
    };

    public static Dictionary<int, string> AttackMap = new Dictionary<int, string>() {
        {0, "Gorgon Tomb - Attack +1"},
        // {0, "Mechanism - Attack +1 (1)"},
        // {0, "Mechanism - Attack +1 (2)"},
        // {0, "Ruins of Ash - Attack +1"},
        // {0, "Catacombs - Attack +1 (1)"},
        // {0, "Catacombs - Attack +1 (2)"},
        // {0, "Catacombs - Attack +1 (3)"},
        // {0, "Catacombs - Attack +1 (4)"},
        // {0, "Catacombs - Attack +1 (5)"},
    };

    public static Dictionary<int, string> HPMap = new Dictionary<int, string>() {
        // {0, "Cyclops Den - Attack +1"},
        // {0, "Cathedral - Attack +1"},
        // {0, "Serpent Path - Attack +1"},
        // {0, "Gorgon Tomb - Max HP +1"},
        // {0, "Gorgon Tomb - Max HP +5"},
        // {0, "Mechanism - Max HP +1"},
        // {0, "Mechanism - Max HP +3"},
        // {0, "Hall of the Phantoms - Max HP +1 (1)"},
        // {0, "Hall of the Phantoms - Max HP +1 (2)"},
        // {0, "Hall of the Phantoms - Max HP +2 (1)"},
        // {0, "Hall of the Phantoms - Max HP +2 (2)"},
        // {0, "Hall of the Phantoms - Max HP +5 (1)"},
        // {0, "Hall of the Phantoms - Max HP +5 (2)"},
        // {0, "Hall of the Phantoms - Max HP +5 (3)"},
        // {0, "Ruins of Ash - Max HP +1"},
        // {0, "Ruins of Ash - Max HP +2"},
        // {0, "Ruins of Ash - Max HP +5"},
        // {0, "The Apex - Max HP +1"},
        // {0, "The Apex - Max HP +5"},
        {6177, "Catacombs - Max HP +1 (1)"}, // first room of catacombs
        // {0, "Catacombs - Max HP +1 (2)"},
        // {0, "Catacombs - Max HP +1 (3)"},
        // {0, "Catacombs - Max HP +2 (1)"},
        // {0, "Catacombs - Max HP +2 (2)"},
        // {0, "Catacombs - Max HP +2 (3)"},
        // {0, "Catacombs - Max HP +2 (4)"},
        // {0, "Catacombs - Max HP +5"},
        // {0, "Tower Roots - Max HP +1"},
        // {0, "Tower Roots - Max HP +2"},
        // {0, "Cyclops Den - Max HP +1"},
        // {0, "Cathedral - Max HP +1 (1)"},
        // {0, "Cathedral - Max HP +1 (2)"},
        // {0, "Cathedral - Max HP +2"},
        // {0, "Cathedral - Max HP +5"},
        // {0, "Serpent Path - Max HP +1"},
    };
}
